# Generated by tools/render_homebrew_formula.sh in Luolc/limae. Edits here are
# overwritten by the next release; change the template in that repository.
class Limae < Formula
  desc "Markdown linter for Chinese technical-writing typography"
  homepage "https://github.com/Luolc/limae"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Luolc/limae/releases/download/v0.13.3/limae-aarch64-apple-darwin.tar.gz"
      sha256 "b92b6f64af273003e11532cde7337be0a9f4e5ca33e869cf362aeb87ab9d1c73"
    end
    on_intel do
      url "https://github.com/Luolc/limae/releases/download/v0.13.3/limae-x86_64-apple-darwin.tar.gz"
      sha256 "1efefbf73e0bac2260e40a876f59d816fefeb10b172f58c0706a0f17ea7db85c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Luolc/limae/releases/download/v0.13.3/limae-aarch64-unknown-linux-musl.tar.gz"
      sha256 "c2d50f6f8dbe8268cc305ee83cba12b52194d75c888e6d8ed006ca13625a69ce"
    end
    on_intel do
      url "https://github.com/Luolc/limae/releases/download/v0.13.3/limae-x86_64-unknown-linux-musl.tar.gz"
      sha256 "d36579c252121d187d948410ea7e256cdbc76bbb0c0087b950ca4a4e48d0ab1e"
    end
  end

  def install
    bin.install "limae"
  end

  test do
    (testpath/"clean.md").write("中文 abc 混排。\n")
    system bin/"limae", "clean.md"

    (testpath/"bad.md").write("中文abc混排。\n")
    assert_match "zh-typography-4", shell_output("#{bin}/limae bad.md", 1)
  end
end
